### ISSUE TITLE
Accounts' utxos

### ISSUE THREAD

**Issue by mmahut** [blockfrost/blockfrost-backend-ryo#192]
Let's add `/accounts/:stake_address/utxos` call if not too heavy.

**Comment by slowbackspace** [comment]
what's the use case? Could such an endpoint even work reliably? If a developer would use it to build a transaction then all I need to do to is sent ADA to my address (payment cred) with attached 3rd party (the developer's) stake cred and I'll break it.

**Comment by Quantumplation** [comment]
We maintain a tool called [Sorbet](https://github.com/SundaeSwap-finance/Sorbet) that lets us emulate a wallet for the purposes of debugging.

The user enters an address and we use blockfrost to look up relevant UTXOs and then implement the CIP-30 interface.

Because of multi-address wallets, this means querying blockfrost for each address that has been associated with the stake address, and then querying the UTXOs for each one of those addresses. In very active wallets this results in hundreds of even thousands of API calls that are just going to return 0 UTXOs.

Being able to query UTXOs by stake address would dramatically simplify this. It's not perfect, and has corner cases like you outline, but since we have no hope of signing transactions from public information, and it's just for helping debug user issues etc., the concern is unlikely to be an issue.

Some alternatives that would work for us:
- query by multiple addresses in one API call
- query for addresses under an account with non-zero balance

**Comment by Quantumplation** [comment]
@slowbackspace @mmahut Any update on this?

**Comment by slowbackspace** [comment]
@Quantumplation We’re on track to have it deployed to preview/preprod by next week!

**Comment by Quantumplation** [comment]
Awesome, ty!

**Comment by slowbackspace** [comment]
@Quantumplation `/accounts/:stake_addr/utxos` is now live on preview and preprod. Mainnet next week if we don't find any issues.

We are still updating docs, but it is basically same as https://docs.blockfrost.io/#tag/cardano--addresses/GET/addresses/{address}/utxos

**Comment by Quantumplation** [comment]
We finally got around to using this, btw; for some wallets, this replaces hundreds of API calls with just 4 API calls in [Sorbet](https://github.com/SundaeSwap-finance/Sorbet)
