### ISSUE TITLE
spent field in the /txs/utxo endpoint

### ISSUE THREAD

**Issue by mmahut** [blockfrost/blockfrost-backend-ryo#202]
We would like to introduce a new field in the /txs/utxo in the outputs, something like `spent: null` if unspent or `spent: 39b034e60e9f16ecd5ceaafac4584c4908816233e431d871a519331ab2e96c3f#0` if spent.

**Comment by slowbackspace** [comment]
just a nitpick, we could do the parsing instead of leaving it to the devs
```
spent: {
   tx_hash: string;
   output_index: number;
}
```

**Comment by sorki** [comment]
I would go with `consumed_by_tx`, similar to a field named in `cardano-db-sync` when `tx_out.consumed` feature is enabled, completely omitting the index due to performance and since refering to input indices is not really common. If really needed one can find it by looking up the referred spending tx.

Now this can be implemented in two ways
- simply using the `consumed_by_tx` field available when insert options has `tx_out.consumed` (we already require custom insert options due to TX CBOR endpoint, I think this needs docs entry)
- using a slower subquery 
```sql 
(
    SELECT txs.hash
    FROM tx txs
    JOIN tx_in txis ON (txis.tx_in_id = txs.id AND txis.tx_out_index = txo.index AND txis.tx_out_id = txo.tx_id)
)  AS "consumed_by_tx"
-- where txo is used as part of the main query
```

I would also keep this as `null` for collateral UTxOs as it's not quite clear how that should be implemented nor it is tracked by `db-sync` similar to `consumed_by_tx` field.
