### ISSUE TITLE
Database indices missing

### ISSUE THREAD

**Issue by MartinSchere** [blockfrost/blockfrost-backend-ryo#39]
There are a few queries that take 30+ seconds to execute, however, Blockfrost as a service usually replies within milliseconds.

I think that in order for this to be usable as self-hosted, the indices created on db-sync need to also be public.

Do you have them available?

**Comment by mmahut** [comment]
There are no additional indices we're using on our db-sync (what we are using, we have already contributed upstream), as we're using the vanilla db-sync version internally too.

Getting data from a large transactional database is always going to be challenging, more so as the data set grows and the reason why you are getting milliseconds replies from the blockfrost.io is because we're using multiple layers of pre-caching of this data.

Also, computing power helps tremendously, more CPU, memory and IOPS speeds up queries significantly.

**Comment by 1000101** [comment]
Hi! Thanks for pointing it out. Although RYO is meant to be run against vanilla db sync, you are right that it can be sluggish on mainnet, since we use already encoded values for most of the queries. Running RYO on testnets is fine (atm), but these indices will increase overall performance on these networks as well.

So, [here they are](https://github.com/blockfrost/blockfrost-backend-ryo/pull/40)!
